Update Travis CI to use standard tests and go 1.9.x.
libp2p/go-libp2p-pnet pull request #14
Opened 2017-11-17 08:07 UTC by kevina

2017-11-17 22:10 UTC, Stebalien approved these changes

2017-11-20 21:36 UTC, Stebalien requested changes

2017-11-20 21:36 UTC, Stebalien commented on .travis.yml
>    directories:
Should have `-race` enabled.

2017-11-20 22:31 UTC, kevina commented on .travis.yml
>    directories:
Done

2017-11-20 22:37 UTC, Stebalien approved these changes

2017-12-05 01:20 UTC, merged